spring:
  data:
    mongodb:
      uri: mongodb://localhost/champions
#spring.data.mongodb.username=
#spring.data.mongodb.password=
api-lol:
  api-key: "RGAPI-61eedb29-591e-4fcf-81b2-cc11c1e80c72"

#server:
  #port : 80