spring:
  data:
    mongodb:
      uri: mongodb://localhost/champions
  devtools:
    remote:
      secret: 123
#spring.data.mongodb.username=
#spring.data.mongodb.password=
api-lol:
  api-key: "RGAPI-88fda7d5-10bd-4d3f-ae1b-555d0f63d415"

#server:
  #port : 80

