spring:
  data:
    mongodb:
       uri: mongodb+srv://root:9O5Q2XmocGJum391@cluster0.4bqt4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
#      host: 172.19.0.2
#      port: 27017
#      database: loldb
#      username: root
#      password: 9O5Q2XmocGJum391

  devtools:
    remote:
      secret: 123
#spring.data.mongodb.username=
#spring.data.mongodb.password=
api-lol:
  api-key: "RGAPI-11d3f8fa-8a84-4fdc-be08-27ce96ecea24"

#server:
  #port : 80

